#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Create or refresh a NixOS host flake that imports Agentic Workstation.

Usage:
  nixos-host-init [options]

Options:
  --target DIR             NixOS config directory (default: /etc/nixos)
  --host NAME              nixosConfigurations name (default: current hostname)
  --system SYSTEM          Nix system (default: detected from uname)
  --profile PROFILE        Agentic Workstation profile (default: coding-agent)
  --source FLAKE           Agentic Workstation flake input (default: github:TAKAMAgents/agentic-workstation-nixos)
  --container-compat       Enable OrbStack/LXC activation compatibility
  --no-container-compat    Disable OrbStack/LXC activation compatibility
  --docker                 Enable Docker through the module
  --no-docker              Disable Docker through the module (default)
  --onepassword            Enable 1Password CLI package
  --no-onepassword         Disable 1Password CLI package (default)
  --force                  Rewrite unmanaged flake.nix or agentic-workstation.nix after creating backups
  --no-lock                Do not run nix flake lock after writing files
  --switch                 Run nixos-rebuild switch after writing files
  -h, --help               Show this help

The target directory must already contain configuration.nix. Existing generated
files are updated in place; unmanaged files require --force and are backed up.
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

detect_system() {
  case "$(uname -m)" in
    aarch64 | arm64) echo "aarch64-linux" ;;
    x86_64 | amd64) echo "x86_64-linux" ;;
    *) die "unsupported architecture: $(uname -m); pass --system explicitly" ;;
  esac
}

detect_host() {
  if [[ -r /proc/sys/kernel/hostname ]]; then
    tr -d '\n' </proc/sys/kernel/hostname
  else
    echo "nixos"
  fi
}

detect_container_compat() {
  if [[ -d /opt/orbstack-guest ]]; then
    echo "true"
    return
  fi

  if command -v systemd-detect-virt >/dev/null 2>&1 && systemd-detect-virt --container >/dev/null 2>&1; then
    echo "true"
    return
  fi

  echo "false"
}

root_cmd() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  elif [[ -x /run/wrappers/bin/sudo ]]; then
    /run/wrappers/bin/sudo "$@"
  else
    sudo "$@"
  fi
}

is_managed_file() {
  local file=$1
  [[ -f "$file" ]] && grep -q "agentic-workstation-nixos:managed-host" "$file"
}

install_generated_file() {
  local source=$1
  local dest=$2
  local force=$3
  local timestamp

  if [[ -e "$dest" ]] && cmp -s "$source" "$dest"; then
    echo "unchanged: $dest"
    return
  fi

  if [[ -e "$dest" ]] && ! is_managed_file "$dest" && [[ "$force" != "true" ]]; then
    die "$dest exists and is not generated by this tool; rerun with --force to back it up and replace it"
  fi

  if [[ -e "$dest" ]]; then
    timestamp="$(date +%Y%m%d%H%M%S)"
    root_cmd cp -a "$dest" "$dest.bak.$timestamp"
    echo "backup: $dest.bak.$timestamp"
  fi

  root_cmd install -m 0644 "$source" "$dest"
  echo "wrote: $dest"
}

target=/etc/nixos
host="$(detect_host)"
system="$(detect_system)"
profile=coding-agent
source_flake=github:TAKAMAgents/agentic-workstation-nixos
container_compat=auto
docker=false
onepassword=false
force=false
lock=true
switch=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      target=${2:-}
      [[ -n "$target" ]] || die "--target requires a value"
      shift 2
      ;;
    --host)
      host=${2:-}
      [[ -n "$host" ]] || die "--host requires a value"
      shift 2
      ;;
    --system)
      system=${2:-}
      [[ -n "$system" ]] || die "--system requires a value"
      shift 2
      ;;
    --profile)
      profile=${2:-}
      [[ -n "$profile" ]] || die "--profile requires a value"
      shift 2
      ;;
    --source)
      source_flake=${2:-}
      [[ -n "$source_flake" ]] || die "--source requires a value"
      shift 2
      ;;
    --container-compat)
      container_compat=true
      shift
      ;;
    --no-container-compat)
      container_compat=false
      shift
      ;;
    --docker)
      docker=true
      shift
      ;;
    --no-docker)
      docker=false
      shift
      ;;
    --onepassword)
      onepassword=true
      shift
      ;;
    --no-onepassword)
      onepassword=false
      shift
      ;;
    --force)
      force=true
      shift
      ;;
    --no-lock)
      lock=false
      shift
      ;;
    --switch)
      switch=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

case "$container_compat" in
  auto) container_compat="$(detect_container_compat)" ;;
  true | false) ;;
  *) die "invalid container compatibility value: $container_compat" ;;
esac

[[ -d "$target" ]] || die "$target does not exist"
[[ -f "$target/configuration.nix" ]] || die "$target/configuration.nix is required"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

cat >"$tmpdir/flake.nix" <<EOF
{
  # agentic-workstation-nixos:managed-host-flake
  description = "Agentic Workstation NixOS host";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    agentic-workstation-nixos.url = "$source_flake";
  };

  outputs = { self, nixpkgs, agentic-workstation-nixos, ... }: {
    nixosConfigurations."$host" = nixpkgs.lib.nixosSystem {
      system = "$system";
      modules = [
        ./configuration.nix
        agentic-workstation-nixos.nixosModules.default
        ./agentic-workstation.nix
      ];
    };
  };
}
EOF

cat >"$tmpdir/agentic-workstation.nix" <<EOF
{ pkgs, ... }:

{
  # agentic-workstation-nixos:managed-host-module
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  programs.agentic-workstation = {
    enable = true;
    profile = "$profile";

    containerCompatibility.enable = $container_compat;
    docker.enable = $docker;
    onePassword.enable = $onepassword;

    direnv.enable = true;
    browserTools.enable = true;
    cloudTools.enable = true;

    extraPackages = with pkgs; [
      neovim
      zellij
      nodejs_22
      git
      gh
      curl
      wget
      jq
      ripgrep
      fd
      bat
      eza
      htop
      just
      tmux
    ];
  };
}
EOF

install_generated_file "$tmpdir/flake.nix" "$target/flake.nix" "$force"
install_generated_file "$tmpdir/agentic-workstation.nix" "$target/agentic-workstation.nix" "$force"

if [[ "$lock" == "true" ]]; then
  root_cmd nix --extra-experimental-features "nix-command flakes" flake lock "$target"
fi

echo
echo "host flake: $target#$host"
echo "profile: $profile"
echo "system: $system"
echo "container compatibility: $container_compat"

if [[ "$switch" == "true" ]]; then
  root_cmd nixos-rebuild switch --flake "$target#$host"
else
  echo
  echo "next: sudo nixos-rebuild switch --flake $target#$host"
fi
